spring:
    application:
        name: payment-service
    cloud:
        config:
            profile: ${PROFILE}
    config:
        import: configserver:http://localhost:8888,optional:file:.env[.properties]
