name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build with Docker Compose
        run: |
          ls -la ${{ github.workspace }}/microservices
          docker-compose -p microservice-test -f ${{ github.workspace }}/microservices/docker-compose.yml up --build -d

      - name: Push Images to DockerHub
        run: docker-compose -p microservice-test -f ${{ github.workspace }}/microservices/docker-compose.yml push
